# Generated by Django 4.1.7 on 2023-03-02 03:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0003_rename_taks_todoitem_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todoitem",
            name="due_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
